name: Test Before Merge
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - staging
      - main
jobs:
  build:
    name: Test Before Merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Typescript check
        run: npm run ci:check
